### ISSUE TITLE
Tracking issue for trait implementations

### ISSUE THREAD

**Issue by newAM** [newAM/ftd2xx-embedded-hal#7]
* [x] I2C
* [x] Delay (not FTDI related)
* [ ] Serial
* [x] SPI
* [ ] [InputPin](https://docs.rs/embedded-hal/0.2.4/embedded_hal/digital/v2/trait.InputPin.html)
* [x] [OuputPin](https://docs.rs/embedded-hal/0.2.4/embedded_hal/digital/v2/trait.OutputPin.html)

**Comment by newAM** [comment]
I2C added in c61374876da242c5866f8e3251c1527065ef6898, unreleased.

**Comment by newAM** [comment]
I2C released in v0.5.1

**Comment by barafael** [comment]
I'd like to try implementing the serial trait. Anything major blocking it?

**Comment by newAM** [comment]
Nothing blocking it, I have just been working on other projects :)
